<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="51922" started-at="2023-02-10T16:45:50Z" finished-at="2023-02-10T16:46:42Z">
    <groups>
    </groups>
    <test name="Demo" duration-ms="51922" started-at="2023-02-10T16:45:50Z" finished-at="2023-02-10T16:46:42Z">
      <class name="TestScript_Demo.DatHangFlows">
        <test-method status="PASS" signature="OpenBrowser()[pri:0, instance:TestScript_Demo.DatHangFlows@7d9d1a19]" name="OpenBrowser" is-config="true" duration-ms="4288" started-at="2023-02-10T16:45:46Z" finished-at="2023-02-10T16:45:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenBrowser -->
        <test-method status="PASS" signature="getDataFromExcelFile()[pri:0, instance:TestScript_Demo.DatHangFlows@7d9d1a19]" name="getDataFromExcelFile" is-config="true" duration-ms="489" started-at="2023-02-10T16:45:50Z" finished-at="2023-02-10T16:45:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getDataFromExcelFile -->
        <test-method status="FAIL" signature="DatHangKhoDC()[pri:1, instance:TestScript_Demo.DatHangFlows@7d9d1a19]" name="DatHangKhoDC" duration-ms="20641" started-at="2023-02-10T16:45:51Z" finished-at="2023-02-10T16:46:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Case thất bại expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Case thất bại expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at TestScript_Demo.DatHangFlows.DatHangKhoDC(DatHangFlows.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DatHangKhoDC -->
        <test-method status="PASS" signature="takeScreenshot(org.testng.ITestResult)[pri:0, instance:TestScript_Demo.DatHangFlows@7d9d1a19]" name="takeScreenshot" is-config="true" duration-ms="325" started-at="2023-02-10T16:46:11Z" finished-at="2023-02-10T16:46:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=DatHangKhoDC status=FAILURE method=DatHangFlows.DatHangKhoDC()[pri:1, instance:TestScript_Demo.DatHangFlows@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenshot -->
        <test-method status="PASS" signature="getDataFromExcelFile()[pri:0, instance:TestScript_Demo.DatHangFlows@7d9d1a19]" name="getDataFromExcelFile" is-config="true" duration-ms="29" started-at="2023-02-10T16:46:12Z" finished-at="2023-02-10T16:46:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getDataFromExcelFile -->
        <test-method status="FAIL" signature="DatHangKhoSieuThi()[pri:2, instance:TestScript_Demo.DatHangFlows@7d9d1a19]" name="DatHangKhoSieuThi" duration-ms="30047" started-at="2023-02-10T16:46:12Z" finished-at="2023-02-10T16:46:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Case thất bại expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Case thất bại expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at TestScript_Demo.DatHangFlows.DatHangKhoSieuThi(DatHangFlows.java:167)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DatHangKhoSieuThi -->
        <test-method status="PASS" signature="takeScreenshot(org.testng.ITestResult)[pri:0, instance:TestScript_Demo.DatHangFlows@7d9d1a19]" name="takeScreenshot" is-config="true" duration-ms="371" started-at="2023-02-10T16:46:42Z" finished-at="2023-02-10T16:46:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=DatHangKhoSieuThi status=FAILURE method=DatHangFlows.DatHangKhoSieuThi()[pri:2, instance:TestScript_Demo.DatHangFlows@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenshot -->
        <test-method status="PASS" signature="CloseBrowser()[pri:0, instance:TestScript_Demo.DatHangFlows@7d9d1a19]" name="CloseBrowser" is-config="true" duration-ms="2726" started-at="2023-02-10T16:46:42Z" finished-at="2023-02-10T16:46:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
      </class> <!-- TestScript_Demo.DatHangFlows -->
    </test> <!-- Demo -->
  </suite> <!-- Suite -->
</testng-results>
